name: My First worklow

on:
  workflow_dispatch:
  push:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
        env:
          GIT_LOG: debug
      - run: |
          echo "Yihaaa!"
        
  
